FROM ubuntu:22.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata
RUN apt-get update && apt-get install -y less gzip wget nginx zip unzip git nano mysql-client
RUN apt-get update && apt-get install --no-install-recommends -y php8.1
RUN apt-get install -y php8.1-fpm php8.1-cli php8.1-common php8.1-mysql php8.1-mbstring php8.1-curl php8.1-xml

RUN mkdir -p /var/www/ocho/api
RUN chown -R www-data:www-data /var/www/ocho/api

COPY nginx.ocho-api.config /etc/nginx/sites-available/ocho-api
RUN rm /etc/nginx/sites-enabled/*
RUN ln -s /etc/nginx/sites-available/ocho-api /etc/nginx/sites-enabled/ocho-api

WORKDIR /var/www/ocho

COPY --from=composer /usr/bin/composer /var/www/ocho/composer.phar
RUN mv /var/www/ocho/composer.phar /usr/local/bin/composer

COPY heartbeat.sh /var/www/ocho/heartbeat.sh
RUN chmod +x heartbeat.sh

CMD ./heartbeat.sh
