<?php

return array (
  'database' => 
  array (
    'default_character_set_name' => 'utf8mb4',
    'default_collation_name' => 'utf8mb4_general_ci',
  ),
  'tables' => 
  array (
    'review_reviews' => 
    array (
      'table' => 
      array (
        'table_name' => 'review_reviews',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'review_reviews',
          'COLUMN_NAME' => 'id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'youtube_url' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'review_reviews',
          'COLUMN_NAME' => 'youtube_url',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'definition' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'review_reviews',
          'COLUMN_NAME' => 'definition',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'mediumtext',
          'CHARACTER_MAXIMUM_LENGTH' => 16777215,
          'CHARACTER_OCTET_LENGTH' => 16777215,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'mediumtext',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'review_reviews',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'ocho_review_reviews2_definition_index' => 
        array (
          1 => 
          array (
            'Table' => 'review_reviews',
            'Non_unique' => 1,
            'Key_name' => 'ocho_review_reviews2_definition_index',
            'Seq_in_index' => 1,
            'Column_name' => 'definition',
            'Collation' => NULL,
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'FULLTEXT',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'tournament_brackets' => 
    array (
      'table' => 
      array (
        'table_name' => 'tournament_brackets',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'bracket_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_brackets',
          'COLUMN_NAME' => 'bracket_id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'tournament_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_brackets',
          'COLUMN_NAME' => 'tournament_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'style_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_brackets',
          'COLUMN_NAME' => 'style_id',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'tournament_brackets_bracket_id_uindex' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_brackets',
            'Non_unique' => 0,
            'Key_name' => 'tournament_brackets_bracket_id_uindex',
            'Seq_in_index' => 1,
            'Column_name' => 'bracket_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'tournament_contestants' => 
    array (
      'table' => 
      array (
        'table_name' => 'tournament_contestants',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'contestant_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_contestants',
          'COLUMN_NAME' => 'contestant_id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'tournament_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_contestants',
          'COLUMN_NAME' => 'tournament_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'people_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_contestants',
          'COLUMN_NAME' => 'people_id',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'contestant' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_contestants',
          'COLUMN_NAME' => 'contestant',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 40,
          'CHARACTER_OCTET_LENGTH' => 160,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(40)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_contestants',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'contestant_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'tournament_id_2' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_contestants',
            'Non_unique' => 0,
            'Key_name' => 'tournament_id_2',
            'Seq_in_index' => 1,
            'Column_name' => 'tournament_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          2 => 
          array (
            'Table' => 'tournament_contestants',
            'Non_unique' => 0,
            'Key_name' => 'tournament_id_2',
            'Seq_in_index' => 2,
            'Column_name' => 'people_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'tournament_id' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_contestants',
            'Non_unique' => 0,
            'Key_name' => 'tournament_id',
            'Seq_in_index' => 1,
            'Column_name' => 'tournament_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          2 => 
          array (
            'Table' => 'tournament_contestants',
            'Non_unique' => 0,
            'Key_name' => 'tournament_id',
            'Seq_in_index' => 2,
            'Column_name' => 'contestant',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'tournament_match' => 
    array (
      'table' => 
      array (
        'table_name' => 'tournament_match',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'match_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'match_id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'tournament_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'tournament_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'bracket_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'bracket_id',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'match_recorded_at' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'match_recorded_at',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'CURRENT_TIMESTAMP',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'heat' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'heat',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 7,
          'CHARACTER_OCTET_LENGTH' => 28,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'enum(\'pit\',\'bracket\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'ring' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'ring',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'reeve' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'reeve',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 40,
          'CHARACTER_OCTET_LENGTH' => 160,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(40)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'reeve_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'reeve_id',
          'ORDINAL_POSITION' => 8,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'contestant_1_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'contestant_1_id',
          'ORDINAL_POSITION' => 9,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'contestant_2_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'contestant_2_id',
          'ORDINAL_POSITION' => 10,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'outcome' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_match',
          'COLUMN_NAME' => 'outcome',
          'ORDINAL_POSITION' => 11,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 12,
          'CHARACTER_OCTET_LENGTH' => 48,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'enum(\'contestant-1\',\'contestant-2\',\'draw\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'tournament_match_match_id_uindex' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_match',
            'Non_unique' => 0,
            'Key_name' => 'tournament_match_match_id_uindex',
            'Seq_in_index' => 1,
            'Column_name' => 'match_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'tournament_people' => 
    array (
      'table' => 
      array (
        'table_name' => 'tournament_people',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'person_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_people',
          'COLUMN_NAME' => 'person_id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'game' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_people',
          'COLUMN_NAME' => 'game',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 9,
          'CHARACTER_OCTET_LENGTH' => 36,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'enum(\'amtgard\',\'belegarth\',\'dagorhir\',\'darkon\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'ork_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_people',
          'COLUMN_NAME' => 'ork_id',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'kingdom' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_people',
          'COLUMN_NAME' => 'kingdom',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 4,
          'CHARACTER_OCTET_LENGTH' => 16,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(4)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'park' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_people',
          'COLUMN_NAME' => 'park',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 4,
          'CHARACTER_OCTET_LENGTH' => 16,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(4)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'person' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_people',
          'COLUMN_NAME' => 'person',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 40,
          'CHARACTER_OCTET_LENGTH' => 160,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(40)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_people',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'person_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'contestant' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_people',
            'Non_unique' => 0,
            'Key_name' => 'contestant',
            'Seq_in_index' => 1,
            'Column_name' => 'person',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          2 => 
          array (
            'Table' => 'tournament_people',
            'Non_unique' => 0,
            'Key_name' => 'contestant',
            'Seq_in_index' => 2,
            'Column_name' => 'kingdom',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          3 => 
          array (
            'Table' => 'tournament_people',
            'Non_unique' => 0,
            'Key_name' => 'contestant',
            'Seq_in_index' => 3,
            'Column_name' => 'park',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          4 => 
          array (
            'Table' => 'tournament_people',
            'Non_unique' => 0,
            'Key_name' => 'contestant',
            'Seq_in_index' => 4,
            'Column_name' => 'game',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => 'YES',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'tournament_reeve' => 
    array (
      'table' => 
      array (
        'table_name' => 'tournament_reeve',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'reeve_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_reeve',
          'COLUMN_NAME' => 'reeve_id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'person_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_reeve',
          'COLUMN_NAME' => 'person_id',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'tournament_reeve_reeve_id_index' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_reeve',
            'Non_unique' => 1,
            'Key_name' => 'tournament_reeve_reeve_id_index',
            'Seq_in_index' => 1,
            'Column_name' => 'reeve_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'tournament_style' => 
    array (
      'table' => 
      array (
        'table_name' => 'tournament_style',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'style_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_style',
          'COLUMN_NAME' => 'style_id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => 'auto_increment',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'style' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_style',
          'COLUMN_NAME' => 'style',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 20,
          'CHARACTER_OCTET_LENGTH' => 80,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(20)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'tournament_style_style_id_uindex' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_style',
            'Non_unique' => 0,
            'Key_name' => 'tournament_style_style_id_uindex',
            'Seq_in_index' => 1,
            'Column_name' => 'style_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'tournament_tournament' => 
    array (
      'table' => 
      array (
        'table_name' => 'tournament_tournament',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_general_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'tournament_id' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_tournament',
          'COLUMN_NAME' => 'tournament_id',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'int',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 10,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'int(11)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'tournament_date' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_tournament',
          'COLUMN_NAME' => 'tournament_date',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'datetime',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'datetime',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'game' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_tournament',
          'COLUMN_NAME' => 'game',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 9,
          'CHARACTER_OCTET_LENGTH' => 36,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'enum(\'amtgard\',\'belegarth\',\'dagorhir\',\'darkon\',\'other\')',
          'COLUMN_KEY' => 'MUL',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'kingdom' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_tournament',
          'COLUMN_NAME' => 'kingdom',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 4,
          'CHARACTER_OCTET_LENGTH' => 16,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(4)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'park' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_tournament',
          'COLUMN_NAME' => 'park',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 4,
          'CHARACTER_OCTET_LENGTH' => 16,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(4)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'event' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_tournament',
          'COLUMN_NAME' => 'event',
          'ORDINAL_POSITION' => 6,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 20,
          'CHARACTER_OCTET_LENGTH' => 80,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(20)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'tournament' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_tournament',
          'COLUMN_NAME' => 'tournament',
          'ORDINAL_POSITION' => 7,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 20,
          'CHARACTER_OCTET_LENGTH' => 80,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'varchar(20)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'pit_style' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_tournament',
          'COLUMN_NAME' => 'pit_style',
          'ORDINAL_POSITION' => 8,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 9,
          'CHARACTER_OCTET_LENGTH' => 36,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'enum(\'none\',\'by-streak\',\'by-win\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'bracket_style' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_tournament',
          'COLUMN_NAME' => 'bracket_style',
          'ORDINAL_POSITION' => 9,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 11,
          'CHARACTER_OCTET_LENGTH' => 44,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'enum(\'single-elim\',\'double-elim\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'bracket_best_of' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'tournament_tournament',
          'COLUMN_NAME' => 'bracket_best_of',
          'ORDINAL_POSITION' => 10,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'enum',
          'CHARACTER_MAXIMUM_LENGTH' => 9,
          'CHARACTER_OCTET_LENGTH' => 36,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_general_ci',
          'COLUMN_TYPE' => 'enum(\'first\',\'best-of-3\',\'best-of-5\')',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_tournament',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'tournament_id',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
        'game' => 
        array (
          1 => 
          array (
            'Table' => 'tournament_tournament',
            'Non_unique' => 0,
            'Key_name' => 'game',
            'Seq_in_index' => 1,
            'Column_name' => 'game',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          2 => 
          array (
            'Table' => 'tournament_tournament',
            'Non_unique' => 0,
            'Key_name' => 'game',
            'Seq_in_index' => 2,
            'Column_name' => 'kingdom',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          3 => 
          array (
            'Table' => 'tournament_tournament',
            'Non_unique' => 0,
            'Key_name' => 'game',
            'Seq_in_index' => 3,
            'Column_name' => 'park',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          4 => 
          array (
            'Table' => 'tournament_tournament',
            'Non_unique' => 0,
            'Key_name' => 'game',
            'Seq_in_index' => 4,
            'Column_name' => 'event',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
          5 => 
          array (
            'Table' => 'tournament_tournament',
            'Non_unique' => 0,
            'Key_name' => 'game',
            'Seq_in_index' => 5,
            'Column_name' => 'tournament',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
    'phinxlog' => 
    array (
      'table' => 
      array (
        'table_name' => 'phinxlog',
        'engine' => 'InnoDB',
        'table_comment' => '',
        'table_collation' => 'utf8mb4_unicode_ci',
        'character_set_name' => 'utf8mb4',
        'row_format' => 'Dynamic',
      ),
      'columns' => 
      array (
        'version' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'version',
          'ORDINAL_POSITION' => 1,
          'COLUMN_DEFAULT' => NULL,
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'bigint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 19,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'bigint(20)',
          'COLUMN_KEY' => 'PRI',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'migration_name' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'migration_name',
          'ORDINAL_POSITION' => 2,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'varchar',
          'CHARACTER_MAXIMUM_LENGTH' => 100,
          'CHARACTER_OCTET_LENGTH' => 400,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => 'utf8mb4',
          'COLLATION_NAME' => 'utf8mb4_unicode_ci',
          'COLUMN_TYPE' => 'varchar(100)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'start_time' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'start_time',
          'ORDINAL_POSITION' => 3,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'end_time' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'end_time',
          'ORDINAL_POSITION' => 4,
          'COLUMN_DEFAULT' => 'NULL',
          'IS_NULLABLE' => 'YES',
          'DATA_TYPE' => 'timestamp',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => NULL,
          'NUMERIC_SCALE' => NULL,
          'DATETIME_PRECISION' => 0,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'timestamp',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
        'breakpoint' => 
        array (
          'TABLE_CATALOG' => 'def',
          'TABLE_NAME' => 'phinxlog',
          'COLUMN_NAME' => 'breakpoint',
          'ORDINAL_POSITION' => 5,
          'COLUMN_DEFAULT' => '0',
          'IS_NULLABLE' => 'NO',
          'DATA_TYPE' => 'tinyint',
          'CHARACTER_MAXIMUM_LENGTH' => NULL,
          'CHARACTER_OCTET_LENGTH' => NULL,
          'NUMERIC_PRECISION' => 3,
          'NUMERIC_SCALE' => 0,
          'DATETIME_PRECISION' => NULL,
          'CHARACTER_SET_NAME' => NULL,
          'COLLATION_NAME' => NULL,
          'COLUMN_TYPE' => 'tinyint(1)',
          'COLUMN_KEY' => '',
          'EXTRA' => '',
          'PRIVILEGES' => 'select,insert,update,references',
          'COLUMN_COMMENT' => '',
          'IS_GENERATED' => 'NEVER',
          'GENERATION_EXPRESSION' => NULL,
        ),
      ),
      'indexes' => 
      array (
        'PRIMARY' => 
        array (
          1 => 
          array (
            'Table' => 'phinxlog',
            'Non_unique' => 0,
            'Key_name' => 'PRIMARY',
            'Seq_in_index' => 1,
            'Column_name' => 'version',
            'Collation' => 'A',
            'Sub_part' => NULL,
            'Packed' => NULL,
            'Null' => '',
            'Index_type' => 'BTREE',
            'Comment' => '',
            'Index_comment' => '',
          ),
        ),
      ),
      'foreign_keys' => NULL,
    ),
  ),
);